language: node_js
node_js:
 - 'stable'
cache:
 directories:
   - 'node_modules'
script:
 - npm run test
after_success:
 - npm run coveralls
 
 services:
  - postgresql

  before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

  addons:
  postgresql: "9.4"